# Generated by Django 3.1 on 2020-08-20 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200820_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('short_description', models.CharField(max_length=64)),
                ('details', models.TextField()),
                ('target', models.DateTimeField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_on', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
