# Generated by Django 3.1 on 2020-08-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
